title: Oracle DBA
description: Oracle database related articles and posts.
theme: just-the-docs

url: https://cashfit.github.io/oracle/

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/cashfit/oracle
